# version: '3.8'
# services:
#   devcontainer:
#     build: 
#       context: .
#       dockerfile: Dockerfile
#     volumes:
#       - .:/app
#   stdin: true
#   tty: true
    # volumes:
    #   - ../..:/workspaces:cached      
    # network_mode: service:db
    # command: sleep infinity

#   db:
#     image: postgres:latest
#     restart: unless-stopped
#     volumes:
#       - postgres-data:/var/lib/postgresql/data
#     environment:
#       POSTGRES_PASSWORD: postgres
#       POSTGRES_USER: postgres
#       POSTGRES_DB: postgres

# volumes:
#   postgres-data:

version: '3.8'
services:
  py-container:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/home/app
    stdin_open: true
    tty: true
